--vim.cmd('source ~/.config/nvim/vimscript/settings.vim')
--vim.cmd('source ~/.config/nvim/vimscript/mappings.vim')
--vim.cmd('source ~/.config/nvim/vimscript/osc52.vim')
--vim.cmd('source ~/.config/nvim/vimscript/functions.vim')
--vim.cmd('source ~/.config/nvim/vimscript/autocmd.vim')

-- General Mappings
require('plugins')
require('nv-globals')
require('nv-utils')
vim.cmd('luafile ~/.config/nvim/nv-settings.lua')
require('keymappings')
require('settings')
 require('colorscheme')
-- require('nv-galaxyline')


-- Plugins
require('nv-compe')
require('nv-colorizer')
require('nv-nvimtree')
require('nv-treesitter')
require('nv-barbar')
require('nv-telescope')
require('nv-lightbulb')
require('nv-vim-rooter')
--require('nv-nvim-dap')
--require('nv-vimspector')
require('nv-gitsigns')
--require('nv-autopairs')
require('nv-nvim-whichkey')


-- LSP
require('lsp')
--require('lsp.clangd')
--require('lsp.lua-ls')
--require('lsp.bash-ls')
require('lsp.go-ls')
require('lsp.python-ls')
require('lsp.rust-ls')
--require('lsp.json-ls')
--require('lsp.yaml-ls')
--require('lsp.terraform-ls')
--require('lsp.vim-ls')
--require('lsp.docker-ls')
--require('lsp.html-ls')
--require('lsp.virtual_text')
